---
- name: Create backend directory
  ansible.builtin.file:
    path: "{{ nginx_paths.backend }}"
    state: directory
    mode: '0755'
    owner: "{{ nginx_linux_user }}"
    group: "{{ nginx_linux_user }}"

- name: List all backend files
  shell: >
    gsutil ls gs://"{{ code_bucket_name }}"/{{bucket_paths.backend}} |
    grep -v /$ |
    awk -F/ '{print $NF}'
  register: backend_files

- name: Fetch all backend files
  google.cloud.gcp_storage_object:
    action: download
    bucket: "{{ code_bucket_name }}"
    src:  "{{ bucket_paths.backend }}/{{ item }}"
    dest: "{{ nginx_paths.backend }}/{{ item }}"
    auth_kind: "application"
    scopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
  loop: "{{ backend_files.stdout_lines }}"
  when: backend_files.stdout_lines is defined
  become_user: "{{ nginx_linux_user }}"
