- name: Install react dependecies for frontend
  community.general.npm:
    path: "{{nginx_paths.frontend}}"
    state: present

- name: Pull frontend env file secret
  google.cloud.gcp_secret_manager:
    name: "{{ secret_name.frontend_env_file }}"
    project: "{{ project }}"
    auth_kind: "machineaccount"
    state: present
  no_log: true
  register: frontend_env_file
  changed_when: true
  notify: Delete secret vars

- name: Create frontend environment file
  ansible.builtin.copy:
    dest: "{{nginx_paths.frontend}}/.env"
    content: |
      {{frontend_env_file.value}}
  notify: Delete frontend .env file

- name: Execute frontend via npm
  ansible.builtin.shell: "nohup npm --prefix {{nginx_paths.frontend}} start >/dev/null 2>&1 &"
