- name: get public ip address
  gcp_compute_address_info:
    filters:
    - name = web-server-public-ip
    region: "{{region}}"
    project: "{{project}}"
    auth_kind: "application"
  register: public_address_info
  no_log: true

- name: Setting a fact for public ip address
  ansible.builtin.set_fact:
    public_address:  "{{public_address_info.resources | map(attribute='address') | first }}" 

- name: Change public DNS to public ip
  ansible.builtin.uri:
    url: https://dynupdate.no-ip.com/nic/update?hostname={{web_nginx_template_file_name}}&myip={{public_address}}
    user: "{{ddns_user.trivia_prod.username}}"
    password: "{{ddns_user.trivia_prod.password}}"

# Certbot automaticlly updates server configuration:
# - runs the server on 443 with certificate from let's encrypt 
# - creates a 301 redirect on 80.
- ansible.builtin.meta: flush_handlers

- name: Configure https using certbot
  shell: |
    certbot --nginx -d "{{web_nginx_template_file_name}}" --email "{{email_for_certificate}}" --agree-tos --non-interactive
  no_log: true
  notify: Restart nginx service