# Certbot automaticlly updates server configuration:
# - runs the server on 443 with certificate from let's encrypt 
# - creates a 301 redirect on 80.
- ansible.builtin.meta: flush_handlers

- name: Configure https using certbot
  shell: |
    certbot --nginx -d "{{web_nginx_template_file_name}}" --email "{{email_for_certificate}}" --agree-tos
  notify: Restart nginx service