---
- name: Install Apt Tools, Including Nginx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ tools.apt }}"


- name: Install Python tools
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{tools.pip}}"
