- name: Add Devopslab User
  community.mysql.mysql_query:
    login_password: "{{ mysql_root_password.value }}"
    query:
    - drop user devopslab@localhost;
    - flush privileges;
    - CREATE USER "devopslab"@"localhost" IDENTIFIED WITH caching_sha2_password BY "{{ devopslab_mysql_user_password }}"
    - GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT on *.* TO 'devopslab'@'localhost' WITH GRANT OPTION;
    - flush privileges;
    single_transaction: True
  no_log: True
