---

- name: Add mysql data directory to mysql disk
  ansible.builtin.file:
    path: "{{ mysqld.datadir_path }}"
    state: directory
    mode: '0755'
    owner: "{{ mysql_linux_user }}"
    group: "{{ mysql_linux_user }}"

- name: Change my.conf
  ansible.builtin.template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart mysql service

- ansible.builtin.meta: flush_handlers

- name: Pull mysql root password from gcp secrets
  google.cloud.gcp_secret_manager:
    name: "{{ mysql_root_password_secret_name }}"
    project: "{{ project }}"
    auth_kind: "machineaccount"
    state: present
  register: mysql_root_password

- name: Set Root Password
  block:
    - name: Set Root Password (Only works if no password is set)
      community.mysql.mysql_query:
        query: ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY "{{ mysql_root_password.value }}"
        login_unix_socket: "{{ mysqld.socket_path }}"
      register: result
      no_log: True
      failed_when:
        - result.changed == false
        - '"using password: NO" not in result.msg'
  always:
    - name: Remove result var
      set_fact:
        result: !!null

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    login_password: "{{ mysql_root_password.value }}"
    name: ''
    host: localhost
    state: absent
