---

- name: Add mysql data directory to mysql disk
  ansible.builtin.file:
    path: "{{ mysqld.datadir_path }}"
    state: directory
    mode: '0755'
    owner: "{{ mysql_linux_user }}"
    group: "{{ mysql_linux_user }}"

- name: Change my.conf
  ansible.builtin.template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart mysql service

- ansible.builtin.meta: flush_handlers

- name: Pull mysql root password from gcp secrets
  google.cloud.gcp_secret_manager:
    name: "{{ mysql_root_password_secret_name }}"
    project: "{{ project }}"
    auth_kind: "machineaccount"
    state: present
  register: mysql_root_password
