---
- name: Create mysql deb package file
  ansible.builtin.file:
    path: "{{ mysql_repository.deb_file }}"
    state: touch
    mode: '0755'

- name: Download Mysql repository deb package
  ansible.builtin.get_url:
    url: "{{ mysql_repository.deb_url }}"
    dest: "{{ mysql_repository.deb_file }}"
    checksum: "{{ mysql_repository.deb_file_checksum }}"

- name: Add Mysql repositories
  ansible.builtin.apt:
    deb: "{{ mysql_repository.deb_file }}"

- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: yes