---

- name: Add mysql data directory to mysql disk
  ansible.builtin.file:
    path: "{{ mysqld.datadir_path }}"
    state: directory
    mode: '0755'
    owner: "{{ mysql_linux_user }}"
    group: "{{ mysql_linux_user }}"

- name: Change my.cnf
  ansible.builtin.template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart mysql service

- ansible.builtin.meta: flush_handlers