- name: Restart nginx service
  service:
    name: nginx
    state: restarted

- name: Delete secret vars
  set_fact:
    backend_env_file: !!null
  no_log: True

- name: Delete backend .env file
  ansible.builtin.file:
    path: "{{nginx_paths.backend}}/.env"
    state: absent

- name: Delete frontend .env file
  ansible.builtin.file:
    path: "{{nginx_paths.frontend}}/.env"
    state: absent

- name: Enable local fw
  community.general.ufw:
    state: enabled
  no_log: True