# Packages to download
tools:
  apt:
    - nginx
    - npm
    - ufw
    - certbot
    - python3-certbot-nginx
  pip:
    - google-cloud-storage

# Nginx
nginx_paths:
  backend:  /usr/nginx/backend
  frontend: /usr/nginx/frontend
  sites_available: /etc/nginx/sites-available
  sites_enabled: /etc/nginx/sites-enabled/
nginx_linux_user: nginx


# Nginx template
frontend_port: 3000
backend_port: 8000
unsafe_server_port: 80
web_nginx_template_file_name: trivia.servegame.com

# Cloud
bucket_paths:
    backend:  Web/backend
    frontend: Web/frontend
secret_name:
  backed_env_file: Backend-Env-File
  frontend_env_file: Frontend-Env-File

# Local fw
firewall_allow_ports:
  - 22
  - "{{unsafe_server_port}}"
  - 443