# Packages to download
tools:
  apt:
    - mysql-server
  pip:
    - PyMySQL

# External repository details
mysql_repository:
  deb_url:
    https://repo.mysql.com/mysql-apt-config_0.8.33-1_all.deb
  deb_file_checksum:
    md5:e1716b19b84b92f32e94dfd34892322c
  deb_file:
    /tmp/mysql-apt-config_0.8.33-1_all.deb
