---
- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ cache_check_time }}"

- name: Install necessary tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ tools }}"