- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: "{{ docker_repository_key.folder_path }}"
    state: directory
    mode: '0755'

- name: Create docker keyring file
  ansible.builtin.file:
    path: "{{ docker_repository_key.file_path }}"
    state: touch
    mode: '0755'

- name: Add Docker repository key
  apt_key:
    url: "{{ docker_repository_key.url }}"
    state: present
    keyring: "{{ docker_repository_key.file_path }}"

- name: Add Docker repository
  ansible.builtin.shell: |
    echo deb  [arch=$(dpkg --print-architecture) signed-by="{{ docker_repository_key.file_path }}"] "{{docker_repository.url}}" \
    xenial stable | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: yes