# Packages to download
tools:
  apt:
    - nginx
  pip:
    - google-cloud-storage

# Nginx
nginx_paths:
  backend:  /usr/nginx/backend
  frontend: /usr/nginx/frontend
nginx_linux_user: nginx

# Cloud
bucket_paths:
    backend:  Web/backend
    frontend: Web/frontend