all:
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_become: true
    ansible_ssh_executable: "{{ ansible_path }}/scripts/gcp-ssh-wrapper.sh"
    ansible_scp_executable: "{{ ansible_path }}/scripts/gcp-scp-wrapper.sh"
    ansible_ssh_common_args: "--internal-ip --zone={{ zone }} --strict-host-key-checking=no"

web_servers:
  hosts:
    web_vm:
      ansible_host: web-server

mysql_servers:
  hosts:
    mysql_vm:
      ansible_host: mysql-server

jenkins_servers:
  hosts:
    jenkins_vm:
      ansible_host: jenkins-server
