all:
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_ssh_executable: "{{ ansible_path }}/scripts/gcp-ssh-wrapper.sh"
    ansible_scp_executable: "{{ ansible_path }}/scripts/gcp-scp-wrapper.sh"
    ansible_ssh_common_args: "--internal-ip --zone={{ zone }} --strict-host-key-checking=no"
    ansible_python_interpreter: "/usr/bin/python3"

webservers:
  hosts:
    web_vm:
      ansible_host: web-server

mysqlservers:
  hosts:
    mysql_vm:
      ansible_host: mysql-server

jenkinsservers:
  hosts:
    jenkins_vm:
      ansible_host: jenkins-server

dockeragentservers:
  hosts:
    docker_agent_vm:
      ansible_host: docker-agent-server
