---
- name: Add jenkins repo
  ansible.builtin.import_tasks: repo_setup.yml

- name: Download jenkins specific tools
  ansible.builtin.import_tasks: tools_setup.yml

- name: Pull secrets from gcp cloud
  ansible.builtin.import_tasks: pull_secrets.yml

- name: Setup Jenkins
  ansible.builtin.import_tasks: setup_jenkins.yml