---
- name: Create jenkins keyring file
  ansible.builtin.file:
    path: "{{ jenkins_repository_key.file_path }}"
    state: touch
    mode: '0755'

- name: Add Jenkins repository key
  apt_key:
    url: "{{ jenkins_repository_key.url }}"
    state: present
    keyring: "{{ jenkins_repository_key.file_path }}"

- name: Adding jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ jenkins_repository_key.file_path }}] {{ jenkins_repository.url }} binary/"
    filename: "{{ jenkins_repository.file }}"
    state: present

- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: yes
