---
- name: Install Apt Tools, Including Jenkins
  apt:
    name: " {{ item }} "
    state: present
  loop: "{{ tools.apt }}"

- name: Install Pip Tools
  ansible.builtin.pip:
    name: " {{ item }} "
    state: present
  loop: "{{ tools.pip }}"