---
- name: Configure Repositories
  hosts: all
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
    - vars/general_vars.yml
  tasks:
  
    - name: Web Group - Install Tools
      apt:
        pkg: "{{group_packages.webservers.apt}}"
        state: present
      when: "'webservers' in group_names"
      tags: webservers

    - name: Web Group - Install python google storage distribution
      ansible.builtin.pip:
        name: "{{ group_packages.webservers.pip }}"
        state: present
      when: "'webservers' in group_names"
      tags: webservers
    
    - name: Mysql Group - Create mysql deb file
      ansible.builtin.file:
        path: "{{mysqlservers.mysql_repository.deb_file}}"
        state: touch
        mode: '0755'
      when: "'mysqlservers' in group_names"
      tags: mysqlservers

    - name: Mysql Group - Download Mysql repository deb package
      ansible.builtin.get_url:
        url: "{{mysqlservers.mysql_repository.deb_url}}"
        dest: "{{mysqlservers.mysql_repository.deb_file}}"
        checksum: "{{mysqlservers.mysql_repository.deb_file_checksum}}"
      when: "'mysqlservers' in group_names"
      tags: mysqlservers

    - name: Mysql Group - Add Mysql repositories
      apt:
        deb: "{{mysqlservers.mysql_repository.deb_file}}"
        update_cache: yes
      when: "'mysqlservers' in group_names"
      tags: mysqlservers
    
    - name: Mysql Group - Add Mysql package
      apt:
        name: mysql-server
      when: "'mysqlservers' in group_names"
      tags: mysqlservers

    - name: Jenkins Group - Install Tools
      apt:
        pkg: "{{group_packages.jenkinsservers.apt}}"
        state: present
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Create jenkins keyring file
      ansible.builtin.file:
        path: "{{ jenkinsservers.jenkins_key.keyring_path }}"
        state: touch
        mode: '0755'
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers

    - name: Jenkins Group - Add Jenkins repository key
      apt_key:
        url: "{{ jenkinsservers.jenkins_key.url }}"
        state: present
        keyring: "{{ jenkinsservers.jenkins_key.keyring_path}}"
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Adding jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ jenkinsservers.jenkins_key.keyring_path}}] {{ jenkinsservers.jenkins_repository.url }} binary/"
        filename: "{{ jenkinsservers.jenkins_repository.file }}"
        state: present
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Install jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
