---
- name: Configure Repositories
  hosts: all
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
    - vars/general_vars.yml
  tasks:
    - name: All groups - Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: All groups - Install necessary tools 
      apt:
        pkg:
          - curl
          - vim
          - htop
          - google-cloud-sdk
        state: present
    
    - name: Web Group - Install Tools
      apt:
        pkg: "{{group_packages.webservers.apt}}"
        state: present
      when: "'webservers' in group_names"

    - name: Web Group - Install python google storage distribution
      ansible.builtin.pip:
        name: "{{ group_packages.webservers.pip }}"
        state: present
      when: "'webservers' in group_names"
