---
- name: Configure Repositories
  hosts: all
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
    - vars/general_vars.yml
  tasks:

    - name: Jenkins Group - Install Tools
      apt:
        pkg: "{{group_packages.jenkinsservers.apt}}"
        state: present
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Create jenkins keyring file
      ansible.builtin.file:
        path: "{{ jenkinsservers.jenkins_key.keyring_path }}"
        state: touch
        mode: '0755'
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers

    - name: Jenkins Group - Add Jenkins repository key
      apt_key:
        url: "{{ jenkinsservers.jenkins_key.url }}"
        state: present
        keyring: "{{ jenkinsservers.jenkins_key.keyring_path}}"
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Adding jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ jenkinsservers.jenkins_key.keyring_path}}] {{ jenkinsservers.jenkins_repository.url }} binary/"
        filename: "{{ jenkinsservers.jenkins_repository.file }}"
        state: present
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
    
    - name: Jenkins Group - Install jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
      when: "'jenkinsservers' in group_names"
      tags: jenkinsservers
