---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars_files:
    - project_vars.yml
    - general_vars.yml
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
    - name: Install necessary tools
      ansible.builtin.apt:
        name:
          - curl
          - vim
          - htop
        state: present
