---
- name: Configure all servers
  hosts: all
  gather_facts: no
  become: true
  vars_files:
    - vars/project_vars.yml
  roles:
    - common

- name: Configure mysql servers
  hosts: mysqlservers
  gather_facts: no
  become: true
  vars_files:
    - vars/project_vars.yml
  roles:
    - { role: mysqlserver, tags: ['mysql'] }

- name: Configure web servers
  hosts: webservers
  gather_facts: no
  become: true
  vars_files:
    - vars/project_vars.yml
  roles:
    - { role: webserver, tags: ['web'] }

- name: Configure jenkins servers
  hosts: jenkinsservers
  gather_facts: no
  become: true
  vars_files:
    - vars/project_vars.yml
  roles:
    - { role: jenkinsserver, tags: ['jenkins'] }