---
- name: Configure all servers
  hosts: all
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
  roles:
    - common

- name: Configure web servers
  hosts: webservers
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
  roles:
    - webserver
