---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars_files:
    - vars/project_vars.yml
    - vars/general_vars.yml
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary tools 
      apt:
        pkg:
          - curl
          - vim
          - htop
          - google-cloud-sdk
        state: present

    - name: Download nginx and pip for Web-Server
      apt:
        pkg:
          - nginx
          - pip
        state: present
      when: inventory_hostname == "web_vm"
    
    - name: Install python google storage distribution
      ansible.builtin.pip:
        name: google-cloud-storage
        state: present
      when: inventory_hostname == "web_vm"
    
    - name: Create the destination directory
      ansible.builtin.file:
        path: /usr/nginx/frontend
        state: directory
        mode: '0755'
        owner: "nginx"
        group: "nginx"
      when: inventory_hostname == "web_vm"

    - name: Copy Web files to Web-Server
      google.cloud.gcp_storage_object:
        action: download
        bucket: "{{ code_bucket_name }}"
        src: "Web/frontend/app.tsx"
        dest: "/usr/nginx/frontend/app.tsx"
        auth_kind: "application"
        scopes: [
                "https://www.googleapis.com/auth/devstorage.read_only"
                ]
      become: yes
      become_user: nginx
      when: inventory_hostname == "web_vm"
